### PR TITLE
Charts

### PR DESCRIPTION
**Pull request by Shoelace**
start of pie charts... for #478 

its currentl showing meat.. and on all tabs..
needs quite a bit of work..  but it is at least showing a chart

### CODE REVIEW

**Comment by erosson** [comment]
looks like this includes a fix for #477 - could merge that now if it were in a separate pull request.

> needs quite a bit of work

waiting to merge this one until you're happier with it.

it might be easier to add the chart to just the territory unit's description, rather than the territory tab's no-unit-selected view: app/views/desc/unit/territory.html , and remove its current description from app/scripts/spreadsheetpreload . (you don't have access to the spreadsheet that generates that, so just edit the generated file by hand and I'll update the spreadsheet later.) that's how I'd planned to do it, though I don't object to adding it to the no-unit-selected view either.

**Comment by Shoelace** [comment]
yes.. sorry.. non chart version here #483

**Comment by Shoelace** [comment]
these charts are quite function now..

did as you sugegsted and moved to territory description.. have 2 charts.. unit count and unit production.

the layout of teh legend is configureable.. i have chosen 'labeled'  but 'right' is the default

see configuration options https://developers.google.com/chart/interactive/docs/gallery/piechart#Configuration_Options 


if we want "meat over time" type graphs we either need to keep a log.. or just update the graph data on a regular basis and just append the current values..

**Comment by Shoelace** [comment]
this is workign quite well now.

moved charts to territory description as suggested

only updates on load.. which is find for now since you need to leave to buy more meat units.

formatting can be adjusted.. options are
https://developers.google.com/chart/interactive/docs/gallery/piechart#Configuration_Options


"meat over time" grpah would be next on list..

**Comment by erosson** [comment]
this is pretty great, thank you! my changes:

* removed the 3d layout (2d fits the game's simple layout better)
* removed tooltips (I couldn't get formatting filters working either)
* percentage entered as percentage, instead of a flat value (support bignums)
* minimum of 1% needed for a unit to appear (keeps things cleaner)
* removed unit count chart (production rates were what most players kept saying they were interested in, and number formatting was hard)
* added a show/hide button, since this is "flashier" than anything the game's seen to date

*****

meat over time would be cool, but you're right, logging it is definitely harder. haven't thought much about how. would probably look into how derivative clicker does their charts for this, how fast they expire logged data/how long they keep it in memory. can't punt on number formatting by using percentages with meat, either.

swarmsim doesn't have to log meat every second to get a graph with every second, btw - only need to log it on every `reify()`. can calculate meat at any time based on that.

**Comment by Shoelace** [comment]
looks great.. i had thought about using actual percentages.. but i didnt know the data structures well enough..

glad i was able to help..

meat over time:.. if you can calulate based on reify().. then yes.. maybe only need to log those.. .. DervitiveClicker on shows graphs for the current session.. which i think is fair.. so dont need to store the log in the savegame..  and just keep a list of updates during game.

we then have points to plot the line.. and we coudl maybe even include a future point for a "swarmwarp" away.

**Comment by erosson** [comment]
> DervitiveClicker on shows graphs for the current session

thanks, good to know. that would make things a lot easier. Still need to expire it at some point to avoid memory-leak-like behavior, but it would simplify a lot to keep this out of saved data.

**Comment by erosson** [comment]
I merged this already. Why doesn't github think I merged it?

Thanks again for putting this together!

**Pull request closed without merging**
